name = "MyPkg"
uuid = "a5351dc5-de12-4edb-8064-82b20ab8fbb5"
authors = ["Jeanne Commault <jeanne.commault@sciencespo.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
